version: '3'
services:
  server:
    build: ./server
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      # - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8001:8001
    command: python3 main.py

  web:
    build: ./web
    ports:
      - 80:80
    depends_on:
      - server
